# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb68c6786f26238eacd5c5ecc20c51a1bbbfda1a898667ab365da42182247e9a4bb8a344dd4d58d4553f9eab6bea59dcac5c8f3882eac067c6849b443fd21495

test:
  secret_key_base: 88f3aade683097493a53ac4f68ba8e8239ca38c2e49d0b14b87eed7da60204e463053f57769e1dd131c0b3817d803f01e3885b6ccaf3206f1e5f2c44d0204fcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
